spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/media_hub?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: hsf1206453X#@!

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

app:
  download:
    dir: /home/video/downloads
  ytdlp:
    path: /usr/local/bin/yt-dlp
    cookies-file: /home/video/cookies.txt
  inpaint:
    python-path: /usr/bin/python3
